APPR6312_Assignment/Models/Disasters.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APPR6312_Assignment.Models
{
    public class Disasters
    {
        [Key]
        [DisplayName("ID")]
        public int disasterID { get; set; }

        [Required]
        [DisplayName("Disaster Name")]
        public string disasterName { get; set; }

        [Required]
        [DisplayName("Start Date")]
        public DateTime disasterStartDate { get; set; }

        [Required]
        [DisplayName("End Date")]
        public DateTime disasterEndDate { get; set; }

        [Required]
        [DisplayName("Disaster Location")]
        public string disasterLocation { get; set; }

        [Required]
        [DisplayName("Aid Type")]
        public string aidType { get; set; }

        [Required]
        [DisplayName("Description")]
        public string disasterDescription { get; set; }

        [Required]
        [DisplayName("Allocated Money")]
        public decimal allocatedMoney { get; set; }

        [Required]
        [DisplayName("Allocated Goods")]
        public int allocatedGoods { get; set; }

        [DisplayName("Goods Category")]
        public string goodsCategory { get; set; }
    }
}

APPR6312_Assignment/Controllers/CashesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APPR6312_Assignment.Models;
using static Microsoft.AspNetCore.Razor.Language.TagHelperMetadata;
using System.Security.Policy;

namespace APPR6312_Assignment.Controllers
{
    public class CashesController : Controller
    {
        private readonly AppDbContext _context;

        public CashesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Cashes
        public async Task<IActionResult> Index()
        {
            ViewBag.email = HttpContext.Session.GetString("email");
            ViewBag.name = HttpContext.Session.GetString("name");
            ViewBag.surname = HttpContext.Session.GetString("surname");

            ViewBag.disaster = HttpContext.Session.GetInt32("disaster");

            return _context.Money != null ?
                          View(await _context.Money.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Money'  is null.");
        }

        // GET: Cashes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Money == null)
            {
                return NotFound();
            }

            var cash = await _context.Money
                .FirstOrDefaultAsync(m => m.moneyID == id);
            if (cash == null)
            {
                return NotFound();
            }

            return View(cash);
        }

        // GET: Cashes/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult AllocateMoney()
        {
            string id = HttpContext.Request.Query["id"];

            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index", "Disasters");
            }

            ViewBag.DisasterID = id;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AllocateMoney(decimal amount, int id)
        {
            var totalMoney = _context.Money.Sum(x => x.moneyAmount);
            ViewBag.totalMoney = totalMoney;

            var remainingMoney = _context.Transactions.Sum(x => x.transAmount);
            ViewBag.remainingMoney = remainingMoney;

            Transaction trans = new Transaction();

            //Amount cannot be lower than 0
            if (remainingMoney < amount)
            {
                ViewBag.error = "Insufficent funds!";
                return View(trans);
            }

            //Task 2 Writting to Transactions Table
            trans.transDate = DateTime.Now;
            trans.transAmount = amount * -1;
            trans.transType = "Allocation";
            _context.Transactions.Add(trans);
            await _context.SaveChangesAsync();

            //LINQ to locate and update the allocatedMoney in the Disaster table when an allocation is made
            Disasters dID = _context.Disaster.FirstOrDefault(x => x.disasterID == id);
            HttpContext.Session.SetInt32("disaster", dID.disasterID);
            ViewBag.disaster = HttpContext.Session.GetInt32("disaster");
            dID.allocatedMoney = dID.allocatedMoney + amount;
            _context.Disaster.Update(dID);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Disasters");
        }

        // POST: Cashes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("moneyID,moneyDate,moneyAmount,goodsDonor")] Cash cash)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cash);

                //Task 2 Writting to Transactions Table
                Transaction trans = new Transaction();
                trans.transDate = cash.moneyDate;
                trans.transAmount = cash.moneyAmount;
                trans.transType = "Donation";
                _context.Add(trans);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cash);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("PublicPage", "Disasters");
        }

        // GET: Cashes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Money == null)
            {
                return NotFound();
            }

            var cash = await _context.Money.FindAsync(id);
            if (cash == null)
            {
                return NotFound();
            }
            return View(cash);
        }

        // POST: Cashes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("moneyID,moneyDate,moneyAmount,goodsDonor")] Cash cash)
        {
            if (id != cash.moneyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cash);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CashExists(cash.moneyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cash);
        }

        // GET: Cashes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Money == null)
            {
                return NotFound();
            }

            var cash = await _context.Money
                .FirstOrDefaultAsync(m => m.moneyID == id);
            if (cash == null)
            {
                return NotFound();
            }

            return View(cash);
        }

        // POST: Cashes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Money == null)
            {
                return Problem("Entity set 'Cash_Context.Money'  is null.");
            }
            var cash = await _context.Money.FindAsync(id);
            if (cash != null)
            {
                _context.Money.Remove(cash);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CashExists(int id)
        {
            return (_context.Money?.Any(e => e.moneyID == id)).GetValueOrDefault();
        }
    }
}

APPR6312_Assignment/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APPR6312_Assignment.Models;
using System.Security.Policy;
using System.Diagnostics;

namespace APPR6312_Assignment.Controllers
{
    public class GoodsController : Controller
    {
        private readonly AppDbContext _context;

        public GoodsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Goods
        public async Task<IActionResult> Index()
        {
            ViewBag.email = HttpContext.Session.GetString("email");
            ViewBag.name = HttpContext.Session.GetString("name");
            ViewBag.surname = HttpContext.Session.GetString("surname");

            ViewBag.disaster = HttpContext.Session.GetString("disaster");

            return _context.Goods != null ? 
                          View(await _context.Goods.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Goods'  is null.");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("PublicPage", "Disasters");
        }

        // GET: Goods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Goods == null)
            {
                return NotFound();
            }

            var good = await _context.Goods
                .FirstOrDefaultAsync(m => m.goodsID == id);
            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        // GET: Goods/Create
        public IActionResult Create()
        {
            var outputList = _context.Goods.Select(x => x.goodsCategory).Distinct().ToList();
            ViewData["Categories"] = outputList;

            return View();
        }

        public IActionResult AllocateGoods()
        {
            string id = HttpContext.Request.Query["id"];

            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index", "Disasters");
            }

            ViewBag.DisasterID = id;

            var outputList = _context.Inventory.Select(x => x.invCategory).Distinct().ToList();
            ViewData["Categories"] = outputList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AllocateGoods(int amount, string category, int id)
        {
            Inventories inv = new Inventories();

            var totalGoods = _context.Goods.Sum(x => x.goodsAmount);
            ViewBag.totalGoods = totalGoods;

            var remainingGoods = _context.Inventory.Sum(x => x.invAmount);
            ViewBag.remainingGoods = remainingGoods;

            var outputList = _context.Inventory.Select(x => x.invCategory).Distinct().ToList();
            ViewData["Categories"] = outputList;

            //Amount cannot be lower than 0
            if (remainingGoods < amount)
            {
                ViewBag.error = "Insufficent goods!";
                return View(inv);
            }

            Disasters dID = _context.Disaster.FirstOrDefault(x => x.disasterID == id);

            HttpContext.Session.SetString("disasterName", dID.disasterName);
            ViewBag.disasterName = HttpContext.Session.GetString("disasterName");

            //Task 2 Writting to Inventory Table
            inv.invDate = DateTime.Now;
            inv.invAmount = amount * -1;
            inv.invCategory = category;
            _context.Inventory.Add(inv);
            await _context.SaveChangesAsync();

            //LINQ to locate and update the allocatedGoods and goodsCategory in the Disaster table when an allocation is made
            HttpContext.Session.SetInt32("disaster", dID.disasterID);
            ViewBag.disaster = HttpContext.Session.GetInt32("disaster");
            dID.allocatedGoods = dID.allocatedGoods + amount;
            dID.goodsCategory = category;
            _context.Disaster.Update(dID);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Disasters");
        }


        // POST: Goods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("goodsID,goodsDate,goodsAmount,goodsDescription,goodsCategory,goodsDonor")] Good good)
        {
            if (ModelState.IsValid)
            {
                _context.Add(good);

                //Task 2 Writting to Inventory Table
                Inventories inv = new Inventories();
                inv.invDate = good.goodsDate;
                inv.invAmount = good.goodsAmount;
                inv.invCategory = good.goodsCategory;
                _context.Add(inv);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(good);
        }

        // GET: Goods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Goods == null)
            {
                return NotFound();
            }

            var good = await _context.Goods.FindAsync(id);
            if (good == null)
            {
                return NotFound();
            }
            return View(good);
        }

        // POST: Goods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("goodsID,goodsDate,goodsAmount,goodsDescription,goodsCategory,goodsDonor")] Good good)
        {
            if (id != good.goodsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(good);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoodExists(good.goodsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(good);
        }

        // GET: Goods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Goods == null)
            {
                return NotFound();
            }

            var good = await _context.Goods
                .FirstOrDefaultAsync(m => m.goodsID == id);
            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        // POST: Goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Goods == null)
            {
                return Problem("Entity set 'Good_Context.Goods'  is null.");
            }
            var good = await _context.Goods.FindAsync(id);
            if (good != null)
            {
                _context.Goods.Remove(good);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoodExists(int id)
        {
          return (_context.Goods?.Any(e => e.goodsID == id)).GetValueOrDefault();
        }
    }
}

APPR6312_Assignment/Views/Disasters/Create.cshtml
@model APPR6312_Assignment.Models.Disasters

@{
    ViewData["Title"] = "Create";
    var name = Accessor.HttpContext.Session.GetString("name");

    var aids = (List<string>)ViewData["Aids"];

}

<h1>Add Disaster</h1>

<h4>Please enter the following details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="disasterName" class="control-label"></label>
                <input asp-for="disasterName" class="form-control" />
                <span asp-validation-for="disasterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterStartDate" class="control-label"></label>
                <input asp-for="disasterStartDate" class="form-control" />
                <span asp-validation-for="disasterStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterEndDate" class="control-label"></label>
                <input asp-for="disasterEndDate" class="form-control" />
                <span asp-validation-for="disasterEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterLocation" class="control-label"></label>
                <input asp-for="disasterLocation" class="form-control" />
                <span asp-validation-for="disasterLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="aidType" class="control-label"></label>
                <input asp-for="aidType" class="form-control" list="aids" />
                <datalist id="aids">
                    @foreach (var item in aids)
                    {
                        <option value="@item"></option>
                    }
                </datalist>
                <span asp-validation-for="aidType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterDescription" class="control-label"></label>
                <input asp-for="disasterDescription" class="form-control" />
                <span asp-validation-for="disasterDescription" class="text-danger"></span>
                <input asp-for="goodsCategory" value="Nothing" hidden/>
            </div>
            <div class="form-group">
                <br>
                <button type="submit" value="Create" class="btn btn-outline-success" >Create</button>
                <button type="button" class="btn btn-outline-warning"><a asp-action="Index">Back to List</a></button>
            </div>
        </form>
    </div>
</div>

APPR6312_Assignment/Views/Disasters/Delete.cshtml
@model APPR6312_Assignment.Models.Disasters

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Disasters</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disasterName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disasterName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disasterStartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disasterStartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disasterEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disasterEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disasterLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disasterLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.aidType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.aidType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disasterDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disasterDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="disasterID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

APPR6312_Assignment/Views/Disasters/Details.cshtml
@model APPR6312_Assignment.Models.Disasters

@{
    ViewData["Title"] = "Details";
}

<h1>Disaster Details</h1>

<div>
    <h4>Details</h4>
    <hr />

    <div class="card bg-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header">Your details</div>
        <div class="card-body">
            <h4 class="card-title">@Html.DisplayNameFor(model => model.disasterName)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.disasterName)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.disasterStartDate)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.disasterStartDate)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.disasterEndDate)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.disasterEndDate)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.disasterLocation)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.disasterLocation)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.aidType)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.aidType)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.disasterDescription)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.disasterDescription)</p>
        </div>
    </div>
</div>

<div>
    <br></br>
    <button type="button" class="btn btn-outline-warning"><a asp-action="Edit" asp-route-id="@Model?.disasterID">Edit</a></button>
    <button type="button" class="btn btn-outline-warning"><a asp-action="Index">Back to List</a></button>

</div>

APPR6312_Assignment/Views/Disasters/Edit.cshtml
@model APPR6312_Assignment.Models.Disasters

@{
    ViewData["Title"] = "Edit";

        var aids = (List<string>)ViewData["Aids"];

}

<h1>Edit</h1>

<h4>Disasters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="disasterID" />
            <div class="form-group">
                <label asp-for="disasterName" class="control-label"></label>
                <input asp-for="disasterName" class="form-control" />
                <span asp-validation-for="disasterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterStartDate" class="control-label"></label>
                <input asp-for="disasterStartDate" class="form-control" />
                <span asp-validation-for="disasterStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterEndDate" class="control-label"></label>
                <input asp-for="disasterEndDate" class="form-control" />
                <span asp-validation-for="disasterEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterLocation" class="control-label"></label>
                <input asp-for="disasterLocation" class="form-control" />
                <span asp-validation-for="disasterLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="aidType" class="control-label"></label>
                <input asp-for="aidType" class="form-control" />
                <span asp-validation-for="aidType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disasterDescription" class="control-label"></label>
                <input asp-for="disasterDescription" class="form-control" />
                <span asp-validation-for="disasterDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="allocatedMoney" class="control-label" hidden></label>
                <input asp-for="allocatedMoney" class="form-control" hidden/>
                <span asp-validation-for="allocatedMoney" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <br>
                <input type="submit" value="Save" class="btn btn-outline-success" />
                <button type="button" class="btn btn-outline-warning"><a asp-action="Index">Back to List</a></button>

            </div>
        </form>
    </div>
</div>

<div>
    
</div>

APPR6312_Assignment/Views/Disasters/Index.cshtml
@model IEnumerable<APPR6312_Assignment.Models.Disasters>

@{
    ViewData["Title"] = "Index";
}

<h1>All Disasters</h1>

<ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Total Money Donated
        <span class="badge bg-info rounded-pill">ZAR @ViewBag.totalMoney</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Remaining Money
        <span class="badge bg-info rounded-pill">ZAR @ViewBag.remainingMoney</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Total Allocations to Disasters
        <span class="badge bg-info rounded-pill">ZAR @ViewBag.totalAllocations</span>
    </li>
</ul>

<br>

<p>
    <button type="button" class="btn btn-outline-secondary"><a asp-action="Create">Add Disaster?</a></button>
    <button class="btn btn-outline-warning" type="button">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminPanel">Back</a>
    </button>
</p>

<table class="table table-hover">
    <thead>
        <tr class="table-info">
            <th scope="col">@Html.DisplayNameFor(model => model.disasterName)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.disasterStartDate)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.disasterEndDate)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.disasterLocation)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.aidType)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.disasterDescription)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.allocatedMoney)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.allocatedGoods)</th>
            <th scope="col">Edit</th>
            <th scope="col">Details</th>
            <th scope="col">Monetary</th>
            <th scope="col">Goods</th>
        </tr>
    </thead>
    <tbody>
        <tr class="table-warning">
            @foreach (var item in Model)
            {
            <tr class="table-warning">
                <td>
                        @Html.DisplayFor(modelItem => item.disasterName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.disasterStartDate)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.disasterEndDate)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.disasterLocation)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.aidType)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.disasterDescription)
                </td>
                <td>
                        ZAR @Html.DisplayFor(modelItem => item.allocatedMoney)
                </td>
                <td>
                         @Html.DisplayFor(modelItem => item.allocatedGoods)
                </td>
                <td>
                     <button type="button" class="btn btn-outline-warning btn-sm"><a asp-action="Edit" asp-route-id="@item.disasterID">Edit</a></button>
                </td>
                <td>
                <button type="button" class="btn btn-outline-warning btn-sm"><a asp-action="Details" asp-route-id="@item.disasterID">Details</a></button>
                </td>
                <td>
                    <button type="button" class="btn btn-outline-warning btn-sm"><a asp-area="" asp-controller="Cashes" asp-action="AllocateMoney" asp-route-id="@item.disasterID">Allocate</a></button>
                </td>
                <td>
                    <button type="button" class="btn btn-outline-warning btn-sm"><a asp-area="" asp-controller="Goods" asp-action="AllocateGoods" asp-route-id="@item.disasterID">Allocate</a></button>
                </td>
            </tr>
            }
    </tbody>
</table>