APPR6312_Assignment/Models/User.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System;

namespace APPR6312_Assignment.Models
{
    public class User
    {
        [Key]
        [DisplayName("Email")]
        [EmailAddress]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string userEmail { get; set; }

        [Required]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,50}$")]
        [StringLength(50, ErrorMessage = "Password must be at least 8 characters long.", MinimumLength = 8)]
        public string userPassword { get; set; }

        [Required]
        [DisplayName("Name")]
        [StringLength(50, MinimumLength = 3)]
        public string userName { get; set; }

        [Required]
        [DisplayName("Surname")]
        [StringLength(50, MinimumLength = 3)]
        public string userSurname { get; set; }

        [Required]
        [DisplayName("Role")]
        public string userRole { get; set; } = "Pending";
    }
}

APPR6312_Assignment/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APPR6312_Assignment.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;
using System.Text;

namespace APPR6312_Assignment.Controllers
{
    public class UsersController : Controller
    {
        private AppDbContext _context;

        User user = new User();

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            ViewBag.email = HttpContext.Session.GetString("email");
            ViewBag.name = HttpContext.Session.GetString("name");
            ViewBag.surname = HttpContext.Session.GetString("surname");

            ViewBag.disaster = HttpContext.Session.GetInt32("disaster");

            var email = HttpContext.Session.GetString("email");

            if (String.IsNullOrWhiteSpace(email))
            {
                return _context.Users != null ?
                              View(await _context.Users.ToListAsync()) :
                              Problem("Entity set 'User_Context.Users'  is null.");
            }

            return _context.Users != null ?
              View(await _context.Users.Where(x => x.userEmail == email).ToListAsync()) :
              Problem("Entity set 'User_Context.Users'  is null.");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("PublicPage", "Disasters");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.userEmail == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        //GET
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Approve(string? email)
        {
            if (!string.IsNullOrWhiteSpace(email))
            {
                var u = _context.Users.Find(email);

                u.userRole = "Approved";

                _context.Update(u);
                _context.SaveChangesAsync();
            }
            return RedirectToAction("ManageUsers");
        }

        [HttpPost]
        public ActionResult Deny(string? email)
        {
            if (!string.IsNullOrWhiteSpace(email))
            {
                var u = _context.Users.Find(email);

                u.userRole = "Denied";

                _context.Update(u);
                _context.SaveChangesAsync();
            }
            return RedirectToAction("ManageUsers");
        }


        public async Task<IActionResult> ManageUsers(User user)
        {
            var details = _context.Users.FirstOrDefault(x => x.userEmail == user.userEmail);

            return _context.Users != null ?
                        View(await _context.Users.Where(x => x.userRole != "Admin").ToListAsync()) :
                        Problem("Entity set 'User_Context.Users'  is null.");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string userEmail, string userPassword)
        {
            if (ModelState.IsValid)
            {
                var details = _context.Users.FirstOrDefault(x => x.userEmail == userEmail);
                var e_password = GetMD5(userPassword);
                var data = _context.Users.Where(s => s.userEmail.Equals(userEmail) && s.userPassword.Equals(e_password)).ToList();

                var vAdmin = _context.Users.Where(a => a.userEmail == userEmail && a.userPassword == e_password && a.userRole == "Admin").FirstOrDefault();
                var vUser = _context.Users.Where(u => u.userEmail == userEmail && u.userPassword == e_password && u.userRole == "Pending").FirstOrDefault();
                var vApproved = _context.Users.Where(u => u.userEmail == userEmail && u.userPassword == e_password && u.userRole == "Approved").FirstOrDefault();
                var vDenied = _context.Users.Where(u => u.userEmail == userEmail && u.userPassword == e_password && u.userRole == "Denied").FirstOrDefault();



                if (details == null)
                {
                    return Login();
                }
                if (userPassword == null)
                {
                    return Login();
                }
                if (details.userPassword != e_password)
                {
                    return Login();
                }

                if (vAdmin != null)
                {
                    HttpContext.Session.SetString("email", details.userEmail);
                    ViewBag.email = HttpContext.Session.GetString("email");
                    HttpContext.Session.SetString("name", details.userName);
                    ViewBag.name = HttpContext.Session.GetString("name");
                    HttpContext.Session.SetString("surname", details.userSurname);
                    ViewBag.surname = HttpContext.Session.GetString("surname");
                    HttpContext.Session.SetString("role", details.userRole);
                    ViewBag.role = HttpContext.Session.GetString("role");

                    return RedirectToAction("AdminPanel", "Home");
                }
                else
                {
                    if (vApproved != null)
                    {
                        HttpContext.Session.SetString("email", details.userEmail);
                        ViewBag.email = HttpContext.Session.GetString("email");
                        HttpContext.Session.SetString("name", details.userName);
                        ViewBag.name = HttpContext.Session.GetString("name");
                        HttpContext.Session.SetString("surname", details.userSurname);
                        ViewBag.surname = HttpContext.Session.GetString("surname");
                        HttpContext.Session.SetString("role", details.userRole);
                        ViewBag.role = HttpContext.Session.GetString("role");

                        return RedirectToAction("Index", "Home");
                    }
                }

                if (vDenied != null)
                {
                    return Login();
                }
            }
            return View();
        }

        //GET
        public IActionResult Register()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                var check = _context.Users.FirstOrDefault(s => s.userEmail == user.userEmail);
                if (check == null)
                {
                    user.userPassword = GetMD5(user.userPassword);
                    _context.Users.Add(user);
                    _context.SaveChanges();
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.error = "Email already exists";
                    return View();
                }
            }

            return View(user);

        }

        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("userEmail,userPassword,userName,userSurname,userRole")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("userEmail,userPassword,userName,userSurname,userRole")] User user)
        {
            if (id != user.userEmail)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    user.userPassword = GetMD5(user.userPassword);
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }

APPR6312_Assignment/Views/Users/Create.cshtml
@model APPR6312_Assignment.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userEmail" class="control-label"></label>
                <input asp-for="userEmail" class="form-control" />
                <span asp-validation-for="userEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userPassword" class="control-label"></label>
                <input asp-for="userPassword" class="form-control" />
                <span asp-validation-for="userPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userSurname" class="control-label"></label>
                <input asp-for="userSurname" class="form-control" />
                <span asp-validation-for="userSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userRole" class="control-label"></label>
                <input asp-for="userRole" class="form-control" />
                <span asp-validation-for="userRole" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

APPR6312_Assignment/Views/Users/Delete.cshtml
@model APPR6312_Assignment.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userSurname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userSurname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userRole)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userRole)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="userEmail" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

APPR6312_Assignment/Views/Users/Details.cshtml
@model APPR6312_Assignment.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Account Information</h1>

<div>
    <h4>Your Details</h4>
    <hr />

    <div class="card bg-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header">Your details</div>
        <div class="card-body">
            <h4 class="card-title">@Html.DisplayNameFor(model => model.userName)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.userName)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.userSurname)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.userSurname)</p>
            <h4 class="card-title">@Html.DisplayNameFor(model => model.userEmail)</h4>
            <p class="card-text">@Html.DisplayFor(model => model.userEmail)</p>
        </div>
    </div>
</div>

<div>
    <br></br>
    <button type="button" class="btn btn-outline-warning"><a asp-action="Edit" asp-route-id="@Model?.userEmail">Edit</a></button>
    <button type="button" class="btn btn-outline-warning"><a asp-action="Index">Back to List</a></button>
    
</div>

APPR6312_Assignment/Views/Users/Edit.cshtml
@model APPR6312_Assignment.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Edit your account details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="userEmail" />
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userSurname" class="control-label"></label>
                <input asp-for="userSurname" class="form-control" />
                <span asp-validation-for="userSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userEmail" class="control-label"></label>
                <input asp-for="userEmail" class="form-control" />
                <span asp-validation-for="userEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userPassword" class="control-label"></label>
                <input asp-for="userPassword" class="form-control" value="" />
                <span asp-validation-for="userPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br></br>
                <input type="submit" value="Save" class="btn btn-outline-success"/>
                <button type="button" class="btn btn-outline-warning"><a asp-action="Index">Back to List</a></button> 
            </div>
        </form>
    </div>
</div>

APPR6312_Assignment/Views/Users/Index.cshtml
@model IEnumerable<APPR6312_Assignment.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Account Details</h1>

<table class="table table-hover">
    <thead>
        <tr class="table-info">
            <th scope="col">@Html.DisplayNameFor(model => model.userName)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.userSurname)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.userEmail)</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <tr class="table-warning">
            @foreach (var item in Model)
            {
            <tr class="table-warning">
                <td>
                        @Html.DisplayFor(modelItem => item.userName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.userSurname)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.userEmail)
                </td>
                <td>
                    <button type="button" class="btn btn-outline-warning btn-sm"><a asp-action="Edit" asp-route-id="@item.userEmail">Edit</a></button>
                    <button type="button" class="btn btn-outline-warning btn-sm"><a asp-action="Details" asp-route-id="@item.userEmail">Details</a></button>
                </td>
            </tr>
            }
    </tbody>
</table>

APPR6312_Assignment/Views/Users/Login.cshtml
@model APPR6312_Assignment.Models.User

@{
	ViewData["Title"] = "Login";
}
<div>
	<form method="post">
		<section class="vh-100 gradient-custom">
			<div class="container py-5 h-100">
				<div class="row d-flex justify-content-center align-items-center h-100">
					<div class="col-12 col-md-8 col-lg-6 col-xl-5">
						<div class="card bg-dark text-white" style="border-radius: 1rem;">
							<div class="card-body p-5 text-center">

								<div class="mb-md-5 mt-md-4 pb-5">

									<h2 class="fw-bold mb-2 text-uppercase">Login</h2>
									<p class="text-white-50 mb-5">Please enter your email and password!</p>

									<div asp-validation-summary="All"></div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userEmail" id="userEmail" class="form-label">Email</label>
										<input asp-for="userEmail" id="userEmail" class="form-control form-control-lg" />
										<span asp-validation-for="userEmail" class="text-danger"></span>

									</div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userPassword" id="userPassword" class="form-label">Password</label>
										<input asp-for="userPassword" type="password" id="userPassword" class="form-control form-control-lg" />
										<span asp-validation-for="userPassword" class="text-danger"></span>
									</div>

									<button class="btn btn-outline-light btn-lg text-dark px-5" type="submit">Login</button>

									    <button class="btn btn-outline-light btn-lg" type="button">
											<a class="nav-link text-dark" asp-area="" asp-controller="Disasters" asp-action="PublicPage">Cancel</a>
										</button>

								</div>

								<div>
									<p class="mb-0">
										Don't have an account? <a href="Register" class="text-white-50 fw-bold">Sign Up</a>
									</p>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</form>
</div>
<div>
</div>

APPR6312_Assignment/Views/Users/ManageUsers.cshtml
@model IEnumerable<APPR6312_Assignment.Models.User>

@{
	ViewData["Title"] = "ManageUsers";
}

<h1>ManageUsers</h1>

<p>
	<button class="btn btn-outline-warning" type="button">
		<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminPanel">Back</a>
	</button>
</p>

<table class="table table-hover">
	<thead>
		<tr class="table-info">
			<th scope="col">@Html.DisplayNameFor(model => model.userName)</th>
			<th scope="col">@Html.DisplayNameFor(model => model.userSurname)</th>
			<th scope="col">@Html.DisplayNameFor(model => model.userEmail)</th>
			<th scope="col">@Html.DisplayNameFor(model => model.userRole)</th>
			<th colspan="2" scope="col" style="text-align: center">Options</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table-warning">
			@foreach (var item in Model)
			{
			<tr class="table-warning">
				<td>
						@Html.DisplayFor(modelItem => item.userName)
				</td>
				<td>
						@Html.DisplayFor(modelItem => item.userSurname)
				</td>
				<td>
						@Html.DisplayFor(modelItem => item.userEmail)
				</td>
				<td>
						@Html.DisplayFor(modelItem => item.userRole)
				</td>
				<td style="text-align: right;">
					<form method="post" asp-action="Approve">
						<input name="email" asp-for="@item.userEmail" hidden />
						<button type="submit" class="btn btn-outline-success btn-sm">Approve</button>
					</form>
				</td>
				<td style="text-align: left;">
					<form method="post" asp-action="Deny">
						<input name="email" asp-for="@item.userEmail" hidden />
						<button type="submit" class="btn btn-outline-danger btn-sm">Deny</button>
					</form>
				</td>
			</tr>
			}
	</tbody>
</table>

APPR6312_Assignment/Views/Users/Register.cshtml
@model APPR6312_Assignment.Models.User

@{
	ViewData["Title"] = "Register";
}
<div>
	<form method="post">
		<section class="vh-100 gradient-custom">
			<div class="container py-5 h-100">
				<div class="row d-flex justify-content-center align-items-center h-100">
					<div class="col-12 col-md-8 col-lg-6 col-xl-5">
						<div class="card bg-dark text-white" style="border-radius: 1rem;">
							<div class="card-body p-5 text-center">

								<div class="mb-md-5 mt-md-4 pb-5">

									<h2 class="fw-bold mb-2 text-uppercase">Register</h2>
									<p class="text-white-50 mb-5">Please enter your details</p>

									<div asp-validation-summary="All"></div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userName" id="userName" class="form-label">Name</label>
										<input asp-for="userName" id="userName" class="form-control form-control-lg" />
										<span asp-validation-for="userName" class="text-danger"></span>
									</div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userSurname" id="userSurname" class="form-label">Surname</label>
										<input asp-for="userSurname" id="userSurname" class="form-control form-control-lg" />
										<span asp-validation-for="userSurname" class="text-danger"></span>
									</div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userEmail" id="userEmail" class="form-label">Email</label>
										<input asp-for="userEmail" id="userEmail" class="form-control form-control-lg" />
										<span asp-validation-for="userEmail" class="text-danger"></span>
									</div>

									<div class="form-outline form-white mb-4">
										<label asp-for="userPassword" id="userPassword" class="form-label">Password</label>
										<input asp-for="userPassword" type="password" id="userPassword" class="form-control form-control-lg" />
										<span asp-validation-for="userPassword" class="text-danger"></span>
									</div>

									<button class="btn btn-outline-light btn-lg px-5 text-dark" type="submit">Register</button>

									<button class="btn btn-outline-light btn-lg" type="button">
										<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Cancel</a>
									</button>

								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</form>
</div>
<div>
</div>